sc.(enable)
!ls = loadsources.(git/surfer/content/sources)
!ls.(main)
!start = loadactivity.(git/surfer/content/activity)
!start.(main)
!inp = userinput.(enable)
!inp.(main)
!inp.(cro.inpconf)
!inpconf.(objects)
!inpconf.(cro.inpobj)
!objlist.(*textarea,multiarea)
